### PR TITLE
feat: Adding Breadcrumbs

### PR DESCRIPTION
**Pull request by jeheskielSunloy77**
1. Adding bradcrumbs component to the application layout.
2. Adding 2 new buttons on home page.

Home page with 2 new buttons, create new training button that wIll open /newTraining page when clicked and more button. and on the top left is the breadcrumb componet 
Screenshot from 2022-08-15 19-42-20

Breadcrumb component is a part of the layout so it will be shown on every page. users can also click on the breadcrumb to navigate to the page.
Screenshot from 2022-08-15 19-44-25

### CODE REVIEW

**Comment by argorfc** [comment]
Before reviews, please add evidence in description column.
As a photo or video.
Thanks

**Comment by jeheskielSunloy77** [comment]
> Before reviews, please add evidence in description column. As a photo or video. Thanks

Ok, i have updated the description.

**Comment by jeheskielSunloy77** [comment]
@argorfc I have updated the description, thank you

**Review by argorfc — APPROVED** [review]
Approved

**Pull request merged**
